<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildProjectDirectory), Build.props))\Build.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>NuGetCredentialProvider</RootNamespace>
    <LangVersion>latest</LangVersion>
    <ApplicationIcon>helpericons.ico</ApplicationIcon>
    <VersionPrefix>$(CredentialProviderVersion)</VersionPrefix>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <NoWarn>$(NoWarn);NU5100</NoWarn>
      <PackAsTool>true</PackAsTool>
      <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
      <PackageId>Microsoft.Artifacts.CredentialProvider.NuGet.Tool</PackageId>
      <ToolCommandName>nuget-plugin-microsoft-artifacts-credential-provider-tool</ToolCommandName>
      <PackageOutputPath>./nupkg</PackageOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
    <DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <DefineConstants>$(DefineConstants);TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.VisualStudioEng.MicroBuild.Core" PrivateAssets="All" />
    <PackageReference Include="NuGet.Protocol" />
    <PackageReference Include="PowerArgs" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Authentication\Microsoft.Artifacts.Authentication.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FilesToSign Include="$(OutDir)$(TargetFileName)" Authenticode="Microsoft400" StrongName="StrongName" />
    <FilesToSign Include="$(IntermediateOutputPath)$(TargetFileName)" Authenticode="Microsoft400" StrongName="StrongName" />
    <FilesToSign Include="$(IntermediateOutputPath)apphost.exe" Condition=" '$(UseAppHost)' == 'true' " Authenticode="Microsoft400" />
  </ItemGroup>
</Project>
