<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>NuGetCredentialProvider</RootNamespace>
    <LangVersion>latest</LangVersion>
    <ApplicationIcon>helpericons.ico</ApplicationIcon>
    <VersionPrefix>$(CredentialProviderVersion)</VersionPrefix>
     <AssemblyName>dotnet-swagger</AssemblyName>
    <IsPackable>true</IsPackable> 
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <NoWarn>$(NoWarn);NU5100</NoWarn>
     <TargetFramework>net8.0</TargetFramework>
        <PackAsTool>true</PackAsTool>
        <PackageId>Credentialprovider.Microsoft</PackageId>
        <ToolCommandName>nuget-plugin-credentialProvider</ToolCommandName>
        <PackageOutputPath>./nupkg</PackageOutputPath>   
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.VisualStudioEng.MicroBuild.Core" PrivateAssets="All" />
    <PackageReference Include="NuGet.Protocol" />
    <PackageReference Include="PowerArgs" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Authentication\Microsoft.Artifacts.Authentication.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FilesToSign Include="$(OutDir)$(TargetFileName)" Authenticode="Microsoft400" StrongName="StrongName" />
    <FilesToSign Include="$(IntermediateOutputPath)$(TargetFileName)" Authenticode="Microsoft400" StrongName="StrongName" />
    <FilesToSign Include="$(IntermediateOutputPath)apphost.exe" Condition=" '$(UseAppHost)' == 'true' " Authenticode="Microsoft400" />
  </ItemGroup>
</Project>
